
version: '3.8'
services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 0
    volumes:
      - .:/app/static
    ports:
      - "3002:3002"
    deploy:
      replicas: 1


